### ISSUE TITLE
Set a niceday tracker reminder

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#170]
As a user I want the virtual agent to set a reminder for a certain tracker if I ask for it.

- [x] Add endpoint to niceday api for setting a reminder for a Niceday tracker
- [x] Add a rasa action for setting a reminder
- [x] Add a small conversation with the user (content doesn't really matter, it is for demo purposes although it should make sense) the endresult of the conversation is setting a reminder for the 'gevoel' tracker.

See the Pull Requests in #20 for where you need to change things.
