### ISSUE TITLE
Make use of custom tracker to set a reminder to track the number of cigarattes smoked

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#19]
- [ ] Upon registration (depends on other issue) enable the custom tracker for smoking ![image](https://user-images.githubusercontent.com/9945255/116558949-3b9a6380-a900-11eb-97f4-382d4f3663a7.png)

- [ ] Set a reminder to track the number of cigarettes smoked
![image](https://user-images.githubusercontent.com/9945255/116558949-3b9a6380-a900-11eb-97f4-382d4f3663a7.png)
![image](https://user-images.githubusercontent.com/9945255/116558987-448b3500-a900-11eb-9b4a-3ce6639d3f2f.png)
- [ ] Make sure to test that this works, maybe the user has to agree on enabling the custom tracker, in that case we have to let user know through the chat.

**Comment by svenvanderburg** [comment]
Blocked by #24
